### ISSUE TITLE
Method closeWebView does not works

### ISSUE THREAD

**Issue by ceifa** [takenet/blip-chat-extension#1]
I want to close my webview when a page loads, like in documentation example. But i'm getting this error:

>Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://mywebsite.com') does not match the recipient window's origin ('https://chat.blip.ai').

Code:

    <script src="https://unpkg.com/blip-chat-extension@1.0.0" type="text/javascript"></script>
    <script>
    (function () {
        window.onload = function () {
            var WebView = new BlipChatExtension()
            WebView.closeWebView()
        }
    })();

**Comment by brenoqueiroz** [comment]
Can u provide a website running the bot with the webview used to close onload

**Comment by VictorBalbo** [comment]
Can you update to latest version 1.0.2?  We fixed this problem there.
